Per default, determine package manager automatically.
svn path=/emacs-updater/; revision=1244

diff --git a/emacs-updater b/emacs-updater
--- a/emacs-updater
+++ b/emacs-updater
@@ -7,7 +7,7 @@
 # Christian Faulhammer <fauli@gentoo.org>
 # Ulrich Mueller <ulm@gentoo.org>
 
-VERSION=1.3
+VERSION=1.4_pre
 EMACS=/usr/bin/emacs
 SITELISP=/usr/share/emacs/site-lisp
 
@@ -15,7 +15,7 @@ SITELISP=/usr/share/emacs/site-lisp
 ACTIONS="sitedir rebuild"
 
 # Default package manager
-PM_COMMAND=pm_portage
+PM_COMMAND=pm_auto
 
 # Other default variable settings
 EXACT=
@@ -48,10 +48,33 @@ usage() {
 	X  -p, --pretend          don't actually emerge packages
 	X  -P, --package-manager <arg>
 	X                         select a package manager. arg is one out of
-	X                         'portage' (default), 'pkgcore', or 'paludis'
+	X                         'portage', 'pkgcore', or 'paludis'
+	X                         (default: automatically determined)
 	X  -h, --help             display this help and exit
 	EOF
     exit ${1}
+}
+
+# Wrapper for package manager commands
+have_portage() { type -P emerge >/dev/null; }
+pm_portage() { emerge --oneshot --ask --verbose "$@"; }
+
+have_pkgcore() { type -P pmerge >/dev/null; }
+pm_pkgcore() { pmerge --oneshot --ask "$@"; }
+
+have_paludis() { type -P paludis >/dev/null; }
+pm_paludis() { paludis --install --preserve-world "$@"; }
+
+pm_auto() {
+    local pm
+    for pm in portage pkgcore paludis; do
+	if have_${pm}; then
+	    pm_${pm} "$@"
+	    return
+	fi
+    done
+    failure "No package manager found"
+    return 1
 }
 
 # Read in all command-line options and force English output
@@ -78,7 +101,7 @@ do
 			;;
 		    *)
 			echo "Invalid action '$action' given!"
-			exit 20
+			usage 20
 			;;
 		esac
 	    done
@@ -86,12 +109,17 @@ do
 	    ;;
 	-P|--package-manager)
 	    case "${2}" in
+		auto|automatic) PM_COMMAND=pm_auto ;;
 		portage|pkgcore|paludis)
+		    if ! "have_${2}"; then
+			echo "Package manager '${2}' not found!"
+			exit 22
+		    fi
 		    PM_COMMAND=pm_${2}
 		    ;;
 		*)
 		    echo "Package manager '${2}' not known!"
-		    exit 21
+		    usage 21
 		    ;;
 	    esac
 	    shift 2
@@ -186,19 +214,6 @@ action_rebuild() {
 
 action_all() {
     action_rebuild all
-}
-
-# Wrapper for package manager commands
-pm_portage() {
-    emerge --oneshot --ask --verbose "$@"
-}
-
-pm_pkgcore() {
-    pmerge --oneshot --ask "$@"
-}
-
-pm_paludis() {
-    paludis --install --preserve-world "$@"
 }
 
 cleanup() {
